# Site settings
title: 
header-img: img/home-bg.png
email: brewer051@gmail.com
copyright_name: brewer051
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  brewer051
learn_profile: brewer051
email_username: brewer051@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
